### ISSUE TITLE
Split the claim txs when getting the huge amount of claims in the `claimtxman`

### ISSUE THREAD

**Issue by jrs-engineer** [0xPolygonHermez/zkevm-bridge-service#399]
## Context

Interacting with a huge amount of claim tx at once caused several problems, the main issue is a `nonce mismatching`.

## Decision

For now, there are two main processes
- create the `monitored tx`
- execute and monitor those txs

To figure out the above problem, it will refactor to three processes
- create the backbone of `monitored tx`, it doesn't include gas and nonce config
- build and sign the `monitored tx` (it will include gas and nonce config), and send tx
- monitor the sent txs and finalize or mark the status of txs

Every time we will interact the fixed amount of txs in the 2nd process.

**Comment by Margana98** [comment]
dear devs.  I did a brige on the zkEVM mainnet polygon to the ethereum mainnet with a successful status but the funds didn't enter me into the ethereum network for 16 hours in polygon official brige tx.  hash 0x26d0a5711a21ec0bb2972888b49527753bb9e9f8c4e83556065b1ee89b6a290b
