### ISSUE TITLE
Can zkevm support multi-chain  bridge? 

### ISSUE THREAD

**Issue by Federico2014** [0xPolygonHermez/zkevm-bridge-service#416]
Can the polygon zkEVM support the multi-chain zkRollup,  which means we can deploy the polygon zkEVM on multiple public chains (ETH, BSC, Solana, etc)?  So the users can deposit the assets from ETH  to zkEVM,  then users also can withdraw the assets from the zkEvm to BSC,  and vice visa.  In this way, the zkEVM can connect multiple public chains. This is convenient for users.
Is there any possible solution to achieve this multi-chain bridge?

**Comment by arnaubennassar** [comment]
The bridge protocol is designed to support multiple chains, and enable L2 to L2 bridges. However, any of those chains using the bridge should be connected to Ethereum in the first place. So no, you can't bridge from ETH to Solana using the zkEVM, or at least not using the native bridge. 3rd party bridges can implement that on the other hand, but in general they have some trust assumptions (compared to the native bridge that is fully secured by Ethereum)
