### ISSUE TITLE
L1 syncing stops, restarts after service restart

### ISSUE THREAD

**Issue by amitOodles** [0xPolygonHermez/zkevm-bridge-service#481]
I am using the code from the branch - https://github.com/0xPolygonHermez/zkevm-bridge-service/tree/v0.0.5-RC2 and running a local zkevm network with Sepolia acting as the L1 layer.

The bridge service stopped syncing the L1 state, and the logs at 
[synchronizer.go](https://github.com/0xPolygonHermez/zkevm-bridge-service/blob/v0.0.5-RC2/synchronizer/synchronizer.go#L204 )
stopped showing.
Syncing with the L2 network was working fine, as the logs with NetworkId 1 were visible throughout that time.

On restarting the bridge service, L1 syncing started again. What is the cause of this issue ?

**Comment by ARR552** [comment]
This bug was fixed time ago in this PR https://github.com/0xPolygonHermez/zkevm-bridge-service/pull/468. Please use the latest version which is v0.2.0
