### ISSUE TITLE
ClaimEvent ABI is error ?? cant unpack log 

### ISSUE THREAD

**Issue by tiantianlikeu** [0xPolygonHermez/zkevm-bridge-service#579]
in contract 
https://github.com/0xPolygonHermez/zkevm-contracts/blob/53e95f3a236d8bea87c27cb8714a5d21496a3b20/contracts/PolygonZkEVMBridge.sol#L115

https://github.com/0xPolygonHermez/zkevm-bridge-service/blob/1c2f0863f22d3eb1fc6a47599b441b2b323aaafa/test/mocksmartcontracts/abi/polygonzkevmbridge.abi#L159C14-L159C21

![image](https://github.com/0xPolygonHermez/zkevm-bridge-service/assets/35363659/b1c92622-75aa-49d9-8f14-8db80f84ddb2)

so this code  is error ???
https://github.com/0xPolygonHermez/zkevm-bridge-service/blob/1c2f0863f22d3eb1fc6a47599b441b2b323aaafa/test/mocksmartcontracts/polygonzkevmbridge/polygonzkevmbridge.go#L1322

**Comment by ARR552** [comment]
Hi, there are different claim events depending on the smc version. Make sure you are using the correct one.
