### ISSUE TITLE
Completed bridge tx show "processing" for a long time

### ISSUE THREAD

**Issue by bap2pecs** [0xPolygonHermez/zkevm-bridge-service#580]
This happens when I first spin up the chain with gasless tx enabled.

The bridge tx is completed (i.e. show up on Metamask, explorer) but on the UI it shows it's "processing"

This kind of issue always fixed by itself after about 30 minutes. This only happen sometimes so there isn't a good way to reproduce it.

The CDK docker image versions used are:
- hermeznetwork/cdk-validium-node:v0.0.3-RC2
- hermeznetwork/zkevm-bridge-service:v0.3.1
- hermeznetwork/zkevm-bridge-ui:mainnet

**Comment by ARR552** [comment]
Hi, probably the problem is the refresh time in the ui. You can open an issue if you are still facing this issue.
