### ISSUE TITLE
Support multiple rollup synchronization

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-bridge-service#595]
This is a collection of known issues that prevent syncing multiple rollups correctly in a single bridge service instance. More than likely to be more problems than the ones reported here:

- [ ] L1 etherman should have an array of supported rollups to filter out events that don't come from rollups that are synced by the service. This happens on functions such as `createNewRollupEvent` and `AddExistingRollupEvent` but there could be others
- [ ] Same for L1 synchronizer, example in `processClaim`
- [ ] previous points need to be addressed from `cmd/run.go` (pass down the interested rollup IDs to L1 {synchronizer, etherman}

**Comment by ARR552** [comment]
For now the networks have to be included in the config file. The service is not able to detect new networks on the fly and add them
