### ISSUE TITLE
L1->L2 bridging is too slow (40+ minutes)

### ISSUE THREAD

**Issue by iszubok** [0xPolygonHermez/zkevm-bridge-service#692]
cdk-erigon beta26
hermeznetwork/zkevm-bridge-service:v0.5.0-RC12

After creating a new network and trying to bridge funds L1->L2, the bridging takes too long.
Current behavior: L2 claim is executed in 40+ minutes after bridge transaction appears on L1, sometimes takes hours
Expected behavior: L2 claim happens right after L1 bridge transaction block is finalized

**Comment by ARR552** [comment]
The problem was in the cdk-erigon node
